version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - go
    commit-message:
      prefix: "chore(deps):"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - ci
    commit-message:
      prefix: "chore(ci):"

  - package-ecosystem: npm
    directory: "/agent"
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - agent
    commit-message:
      prefix: "chore(deps):"
