// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package kraclawv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this gene...
const _ = grpc.SupportPackageIsVersion9

const (
	AuthService_StartChatGPTDeviceAuth_FullMethodName = "/kraclaw.v1.AuthService/StartChatGPTDeviceAuth"
)

// AuthServiceClient is the client API for AuthService service.
type AuthServiceClient interface {
// StartChatGPTDeviceAuth begins the OAuth 2.0 device-code f...
	StartChatGPTDeviceAuth(ctx context.Context, in *StartChatGPTDeviceAuthRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DeviceAuthEvent], error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) StartChatGPTDeviceAuth(ctx context.Context, in *StartChatGPTDeviceAuthRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DeviceAuthEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AuthService_ServiceDesc.Streams[0], AuthService_StartChatGPTDeviceAuth_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StartChatGPTDeviceAuthRequest, DeviceAuthEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AuthService_StartChatGPTDeviceAuthClient = grpc.ServerStreamingClient[DeviceAuthEvent]

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
// StartChatGPTDeviceAuth begins the OAuth 2.0 device-code f...
	StartChatGPTDeviceAuth(*StartChatGPTDeviceAuthRequest, grpc.ServerStreamingServer[DeviceAuthEvent]) error
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) StartChatGPTDeviceAuth(*StartChatGPTDeviceAuthRequest, grpc.ServerStreamingServer[DeviceAuthEvent]) error {
	return status.Error(codes.Unimplemented, "method StartChatGPTDeviceAuth not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}
func (UnimplementedAuthServiceServer) testEmbeddedByValue()                     {}

// UnsafeAuthServiceServer may be embedded to opt out of for...
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
// If the following call panics, it indicates UnimplementedA...
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_StartChatGPTDeviceAuth_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StartChatGPTDeviceAuthRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AuthServiceServer).StartChatGPTDeviceAuth(m, &grpc.GenericServerStream[StartChatGPTDeviceAuthRequest, DeviceAuthEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AuthService_StartChatGPTDeviceAuthServer = grpc.ServerStreamingServer[DeviceAuthEvent]

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthS...
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kraclaw.v1.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StartChatGPTDeviceAuth",
			Handler:       _AuthService_StartChatGPTDeviceAuth_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "kraclaw/v1/auth.proto",
}
