// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kraclaw/v1/auth.proto

package kraclawv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorCode is the terminal error category surfaced to clients. The server
// emits exactly one Error event with one of these codes, then closes the
// stream. Order: ERROR_CODE_UNSPECIFIED is the proto3 default and MUST NOT
// be emitted; clients seeing it should treat as an internal protocol bug.
type DeviceAuthEvent_ErrorCode int32

const (
	DeviceAuthEvent_ERROR_CODE_UNSPECIFIED DeviceAuthEvent_ErrorCode = 0
	DeviceAuthEvent_INTERNAL               DeviceAuthEvent_ErrorCode = 1
	DeviceAuthEvent_INVALID_ARGUMENT       DeviceAuthEvent_ErrorCode = 2
	DeviceAuthEvent_TIMEOUT                DeviceAuthEvent_ErrorCode = 3
	DeviceAuthEvent_ACCESS_DENIED          DeviceAuthEvent_ErrorCode = 4
	DeviceAuthEvent_CANCELLED              DeviceAuthEvent_ErrorCode = 5
)

// Enum value maps for DeviceAuthEvent_ErrorCode.
var (
	DeviceAuthEvent_ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNSPECIFIED",
		1: "INTERNAL",
		2: "INVALID_ARGUMENT",
		3: "TIMEOUT",
		4: "ACCESS_DENIED",
		5: "CANCELLED",
	}
	DeviceAuthEvent_ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED": 0,
		"INTERNAL":               1,
		"INVALID_ARGUMENT":       2,
		"TIMEOUT":                3,
		"ACCESS_DENIED":          4,
		"CANCELLED":              5,
	}
)

func (x DeviceAuthEvent_ErrorCode) Enum() *DeviceAuthEvent_ErrorCode {
	p := new(DeviceAuthEvent_ErrorCode)
	*p = x
	return p
}

func (x DeviceAuthEvent_ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceAuthEvent_ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_kraclaw_v1_auth_proto_enumTypes[0].Descriptor()
}

func (DeviceAuthEvent_ErrorCode) Type() protoreflect.EnumType {
	return &file_kraclaw_v1_auth_proto_enumTypes[0]
}

func (x DeviceAuthEvent_ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceAuthEvent_ErrorCode.Descriptor instead.
func (DeviceAuthEvent_ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_kraclaw_v1_auth_proto_rawDescGZIP(), []int{1, 0}
}

type StartChatGPTDeviceAuthRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// group_jid identifies the per-group credential row (PR #46 schema).
	GroupJid string `protobuf:"bytes,1,opt,name=group_jid,json=groupJid,proto3" json:"group_jid,omitempty"`
	// provider must be a registry provider id with auth_mode == "chatgpt"
	// (today: "openai").
	Provider      string `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartChatGPTDeviceAuthRequest) Reset() {
	*x = StartChatGPTDeviceAuthRequest{}
	mi := &file_kraclaw_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartChatGPTDeviceAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartChatGPTDeviceAuthRequest) ProtoMessage() {}

func (x *StartChatGPTDeviceAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartChatGPTDeviceAuthRequest.ProtoReflect.Descriptor instead.
func (*StartChatGPTDeviceAuthRequest) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *StartChatGPTDeviceAuthRequest) GetGroupJid() string {
	if x != nil {
		return x.GroupJid
	}
	return ""
}

func (x *StartChatGPTDeviceAuthRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type DeviceAuthEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*DeviceAuthEvent_DeviceCode_
	//	*DeviceAuthEvent_Tick_
	//	*DeviceAuthEvent_Success_
	//	*DeviceAuthEvent_Error_
	Event         isDeviceAuthEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceAuthEvent) Reset() {
	*x = DeviceAuthEvent{}
	mi := &file_kraclaw_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceAuthEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceAuthEvent) ProtoMessage() {}

func (x *DeviceAuthEvent) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceAuthEvent.ProtoReflect.Descriptor instead.
func (*DeviceAuthEvent) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceAuthEvent) GetEvent() isDeviceAuthEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *DeviceAuthEvent) GetDeviceCode() *DeviceAuthEvent_DeviceCode {
	if x != nil {
		if x, ok := x.Event.(*DeviceAuthEvent_DeviceCode_); ok {
			return x.DeviceCode
		}
	}
	return nil
}

func (x *DeviceAuthEvent) GetTick() *DeviceAuthEvent_Tick {
	if x != nil {
		if x, ok := x.Event.(*DeviceAuthEvent_Tick_); ok {
			return x.Tick
		}
	}
	return nil
}

func (x *DeviceAuthEvent) GetSuccess() *DeviceAuthEvent_Success {
	if x != nil {
		if x, ok := x.Event.(*DeviceAuthEvent_Success_); ok {
			return x.Success
		}
	}
	return nil
}

func (x *DeviceAuthEvent) GetError() *DeviceAuthEvent_Error {
	if x != nil {
		if x, ok := x.Event.(*DeviceAuthEvent_Error_); ok {
			return x.Error
		}
	}
	return nil
}

type isDeviceAuthEvent_Event interface {
	isDeviceAuthEvent_Event()
}

type DeviceAuthEvent_DeviceCode_ struct {
	DeviceCode *DeviceAuthEvent_DeviceCode `protobuf:"bytes,1,opt,name=device_code,json=deviceCode,proto3,oneof"`
}

type DeviceAuthEvent_Tick_ struct {
	Tick *DeviceAuthEvent_Tick `protobuf:"bytes,2,opt,name=tick,proto3,oneof"`
}

type DeviceAuthEvent_Success_ struct {
	Success *DeviceAuthEvent_Success `protobuf:"bytes,3,opt,name=success,proto3,oneof"`
}

type DeviceAuthEvent_Error_ struct {
	Error *DeviceAuthEvent_Error `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*DeviceAuthEvent_DeviceCode_) isDeviceAuthEvent_Event() {}

func (*DeviceAuthEvent_Tick_) isDeviceAuthEvent_Event() {}

func (*DeviceAuthEvent_Success_) isDeviceAuthEvent_Event() {}

func (*DeviceAuthEvent_Error_) isDeviceAuthEvent_Event() {}

type DeviceAuthEvent_DeviceCode struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserCode        string                 `protobuf:"bytes,1,opt,name=user_code,json=userCode,proto3" json:"user_code,omitempty"`
	VerificationUrl string                 `protobuf:"bytes,2,opt,name=verification_url,json=verificationUrl,proto3" json:"verification_url,omitempty"`
	// poll_interval_seconds is informational; the server polls itself.
	PollIntervalSeconds int32 `protobuf:"varint,3,opt,name=poll_interval_seconds,json=pollIntervalSeconds,proto3" json:"poll_interval_seconds,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DeviceAuthEvent_DeviceCode) Reset() {
	*x = DeviceAuthEvent_DeviceCode{}
	mi := &file_kraclaw_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceAuthEvent_DeviceCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceAuthEvent_DeviceCode) ProtoMessage() {}

func (x *DeviceAuthEvent_DeviceCode) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceAuthEvent_DeviceCode.ProtoReflect.Descriptor instead.
func (*DeviceAuthEvent_DeviceCode) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_auth_proto_rawDescGZIP(), []int{1, 0}
}

func (x *DeviceAuthEvent_DeviceCode) GetUserCode() string {
	if x != nil {
		return x.UserCode
	}
	return ""
}

func (x *DeviceAuthEvent_DeviceCode) GetVerificationUrl() string {
	if x != nil {
		return x.VerificationUrl
	}
	return ""
}

func (x *DeviceAuthEvent_DeviceCode) GetPollIntervalSeconds() int32 {
	if x != nil {
		return x.PollIntervalSeconds
	}
	return 0
}

type DeviceAuthEvent_Tick struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// elapsed_seconds since the device-code event.
	ElapsedSeconds int32 `protobuf:"varint,1,opt,name=elapsed_seconds,json=elapsedSeconds,proto3" json:"elapsed_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeviceAuthEvent_Tick) Reset() {
	*x = DeviceAuthEvent_Tick{}
	mi := &file_kraclaw_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceAuthEvent_Tick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceAuthEvent_Tick) ProtoMessage() {}

func (x *DeviceAuthEvent_Tick) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceAuthEvent_Tick.ProtoReflect.Descriptor instead.
func (*DeviceAuthEvent_Tick) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_auth_proto_rawDescGZIP(), []int{1, 1}
}

func (x *DeviceAuthEvent_Tick) GetElapsedSeconds() int32 {
	if x != nil {
		return x.ElapsedSeconds
	}
	return 0
}

type DeviceAuthEvent_Success struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// account_id is the parsed sub claim from id_token; useful for display.
	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// expires_at is RFC3339; informational only.
	ExpiresAt     string `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceAuthEvent_Success) Reset() {
	*x = DeviceAuthEvent_Success{}
	mi := &file_kraclaw_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceAuthEvent_Success) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceAuthEvent_Success) ProtoMessage() {}

func (x *DeviceAuthEvent_Success) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceAuthEvent_Success.ProtoReflect.Descriptor instead.
func (*DeviceAuthEvent_Success) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_auth_proto_rawDescGZIP(), []int{1, 2}
}

func (x *DeviceAuthEvent_Success) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *DeviceAuthEvent_Success) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type DeviceAuthEvent_Error struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Code          DeviceAuthEvent_ErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=kraclaw.v1.DeviceAuthEvent_ErrorCode" json:"code,omitempty"`
	Message       string                    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceAuthEvent_Error) Reset() {
	*x = DeviceAuthEvent_Error{}
	mi := &file_kraclaw_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceAuthEvent_Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceAuthEvent_Error) ProtoMessage() {}

func (x *DeviceAuthEvent_Error) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceAuthEvent_Error.ProtoReflect.Descriptor instead.
func (*DeviceAuthEvent_Error) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_auth_proto_rawDescGZIP(), []int{1, 3}
}

func (x *DeviceAuthEvent_Error) GetCode() DeviceAuthEvent_ErrorCode {
	if x != nil {
		return x.Code
	}
	return DeviceAuthEvent_ERROR_CODE_UNSPECIFIED
}

func (x *DeviceAuthEvent_Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_kraclaw_v1_auth_proto protoreflect.FileDescriptor

const file_kraclaw_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x15kraclaw/v1/auth.proto\x12\n" +
	"kraclaw.v1\"X\n" +
	"\x1dStartChatGPTDeviceAuthRequest\x12\x1b\n" +
	"\tgroup_jid\x18\x01 \x01(\tR\bgroupJid\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\"\xf8\x05\n" +
	"\x0fDeviceAuthEvent\x12I\n" +
	"\vdevice_code\x18\x01 \x01(\v2&.kraclaw.v1.DeviceAuthEvent.DeviceCodeH\x00R\n" +
	"deviceCode\x126\n" +
	"\x04tick\x18\x02 \x01(\v2 .kraclaw.v1.DeviceAuthEvent.TickH\x00R\x04tick\x12?\n" +
	"\asuccess\x18\x03 \x01(\v2#.kraclaw.v1.DeviceAuthEvent.SuccessH\x00R\asuccess\x129\n" +
	"\x05error\x18\x04 \x01(\v2!.kraclaw.v1.DeviceAuthEvent.ErrorH\x00R\x05error\x1a\x88\x01\n" +
	"\n" +
	"DeviceCode\x12\x1b\n" +
	"\tuser_code\x18\x01 \x01(\tR\buserCode\x12)\n" +
	"\x10verification_url\x18\x02 \x01(\tR\x0fverificationUrl\x122\n" +
	"\x15poll_interval_seconds\x18\x03 \x01(\x05R\x13pollIntervalSeconds\x1a/\n" +
	"\x04Tick\x12'\n" +
	"\x0felapsed_seconds\x18\x01 \x01(\x05R\x0eelapsedSeconds\x1aG\n" +
	"\aSuccess\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\tR\texpiresAt\x1a\\\n" +
	"\x05Error\x129\n" +
	"\x04code\x18\x01 \x01(\x0e2%.kraclaw.v1.DeviceAuthEvent.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"z\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bINTERNAL\x10\x01\x12\x14\n" +
	"\x10INVALID_ARGUMENT\x10\x02\x12\v\n" +
	"\aTIMEOUT\x10\x03\x12\x11\n" +
	"\rACCESS_DENIED\x10\x04\x12\r\n" +
	"\tCANCELLED\x10\x05B\a\n" +
	"\x05event2q\n" +
	"\vAuthService\x12b\n" +
	"\x16StartChatGPTDeviceAuth\x12).kraclaw.v1.StartChatGPTDeviceAuthRequest\x1a\x1b.kraclaw.v1.DeviceAuthEvent0\x01B\x9a\x01\n" +
	"\x0ecom.kraclaw.v1B\tAuthProtoP\x01Z4github.com/johanssonvincent/kraclaw/pkg/pb/kraclawv1\xa2\x02\x03KXX\xaa\x02\n" +
	"Kraclaw.V1\xca\x02\n" +
	"Kraclaw\\V1\xe2\x02\x16Kraclaw\\V1\\GPBMetadata\xea\x02\vKraclaw::V1b\x06proto3"

var (
	file_kraclaw_v1_auth_proto_rawDescOnce sync.Once
	file_kraclaw_v1_auth_proto_rawDescData []byte
)

func file_kraclaw_v1_auth_proto_rawDescGZIP() []byte {
	file_kraclaw_v1_auth_proto_rawDescOnce.Do(func() {
		file_kraclaw_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kraclaw_v1_auth_proto_rawDesc), len(file_kraclaw_v1_auth_proto_rawDesc)))
	})
	return file_kraclaw_v1_auth_proto_rawDescData
}

var file_kraclaw_v1_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kraclaw_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_kraclaw_v1_auth_proto_goTypes = []any{
	(DeviceAuthEvent_ErrorCode)(0),        // 0: kraclaw.v1.DeviceAuthEvent.ErrorCode
	(*StartChatGPTDeviceAuthRequest)(nil), // 1: kraclaw.v1.StartChatGPTDeviceAuthRequest
	(*DeviceAuthEvent)(nil),               // 2: kraclaw.v1.DeviceAuthEvent
	(*DeviceAuthEvent_DeviceCode)(nil),    // 3: kraclaw.v1.DeviceAuthEvent.DeviceCode
	(*DeviceAuthEvent_Tick)(nil),          // 4: kraclaw.v1.DeviceAuthEvent.Tick
	(*DeviceAuthEvent_Success)(nil),       // 5: kraclaw.v1.DeviceAuthEvent.Success
	(*DeviceAuthEvent_Error)(nil),         // 6: kraclaw.v1.DeviceAuthEvent.Error
}
var file_kraclaw_v1_auth_proto_depIdxs = []int32{
	3, // 0: kraclaw.v1.DeviceAuthEvent.device_code:type_name -> kraclaw.v1.DeviceAuthEvent.DeviceCode
	4, // 1: kraclaw.v1.DeviceAuthEvent.tick:type_name -> kraclaw.v1.DeviceAuthEvent.Tick
	5, // 2: kraclaw.v1.DeviceAuthEvent.success:type_name -> kraclaw.v1.DeviceAuthEvent.Success
	6, // 3: kraclaw.v1.DeviceAuthEvent.error:type_name -> kraclaw.v1.DeviceAuthEvent.Error
	0, // 4: kraclaw.v1.DeviceAuthEvent.Error.code:type_name -> kraclaw.v1.DeviceAuthEvent.ErrorCode
	1, // 5: kraclaw.v1.AuthService.StartChatGPTDeviceAuth:input_type -> kraclaw.v1.StartChatGPTDeviceAuthRequest
	2, // 6: kraclaw.v1.AuthService.StartChatGPTDeviceAuth:output_type -> kraclaw.v1.DeviceAuthEvent
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_kraclaw_v1_auth_proto_init() }
func file_kraclaw_v1_auth_proto_init() {
	if File_kraclaw_v1_auth_proto != nil {
		return
	}
	file_kraclaw_v1_auth_proto_msgTypes[1].OneofWrappers = []any{
		(*DeviceAuthEvent_DeviceCode_)(nil),
		(*DeviceAuthEvent_Tick_)(nil),
		(*DeviceAuthEvent_Success_)(nil),
		(*DeviceAuthEvent_Error_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kraclaw_v1_auth_proto_rawDesc), len(file_kraclaw_v1_auth_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kraclaw_v1_auth_proto_goTypes,
		DependencyIndexes: file_kraclaw_v1_auth_proto_depIdxs,
		EnumInfos:         file_kraclaw_v1_auth_proto_enumTypes,
		MessageInfos:      file_kraclaw_v1_auth_proto_msgTypes,
	}.Build()
	File_kraclaw_v1_auth_proto = out.File
	file_kraclaw_v1_auth_proto_goTypes = nil
	file_kraclaw_v1_auth_proto_depIdxs = nil
}
