// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kraclaw/v1/group.proto

package kraclawv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Group struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Jid                 string                 `protobuf:"bytes,1,opt,name=jid,proto3" json:"jid,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Folder              string                 `protobuf:"bytes,3,opt,name=folder,proto3" json:"folder,omitempty"`
	TriggerPattern      string                 `protobuf:"bytes,4,opt,name=trigger_pattern,json=triggerPattern,proto3" json:"trigger_pattern,omitempty"`
	IsMain              bool                   `protobuf:"varint,5,opt,name=is_main,json=isMain,proto3" json:"is_main,omitempty"`
	RequiresTrigger     bool                   `protobuf:"varint,6,opt,name=requires_trigger,json=requiresTrigger,proto3" json:"requires_trigger,omitempty"`
	ContainerConfigJson string                 `protobuf:"bytes,7,opt,name=container_config_json,json=containerConfigJson,proto3" json:"container_config_json,omitempty"`
	AddedAt             *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=added_at,json=addedAt,proto3" json:"added_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_kraclaw_v1_group_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_group_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_group_proto_rawDescGZIP(), []int{0}
}

func (x *Group) GetJid() string {
	if x != nil {
		return x.Jid
	}
	return ""
}

func (x *Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Group) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

func (x *Group) GetTriggerPattern() string {
	if x != nil {
		return x.TriggerPattern
	}
	return ""
}

func (x *Group) GetIsMain() bool {
	if x != nil {
		return x.IsMain
	}
	return false
}

func (x *Group) GetRequiresTrigger() bool {
	if x != nil {
		return x.RequiresTrigger
	}
	return false
}

func (x *Group) GetContainerConfigJson() string {
	if x != nil {
		return x.ContainerConfigJson
	}
	return ""
}

func (x *Group) GetAddedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AddedAt
	}
	return nil
}

type RegisterGroupRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Jid                 string                 `protobuf:"bytes,1,opt,name=jid,proto3" json:"jid,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Folder              string                 `protobuf:"bytes,3,opt,name=folder,proto3" json:"folder,omitempty"`
	TriggerPattern      string                 `protobuf:"bytes,4,opt,name=trigger_pattern,json=triggerPattern,proto3" json:"trigger_pattern,omitempty"`
	IsMain              bool                   `protobuf:"varint,5,opt,name=is_main,json=isMain,proto3" json:"is_main,omitempty"`
	RequiresTrigger     bool                   `protobuf:"varint,6,opt,name=requires_trigger,json=requiresTrigger,proto3" json:"requires_trigger,omitempty"`
	ContainerConfigJson string                 `protobuf:"bytes,7,opt,name=container_config_json,json=containerConfigJson,proto3" json:"container_config_json,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RegisterGroupRequest) Reset() {
	*x = RegisterGroupRequest{}
	mi := &file_kraclaw_v1_group_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterGroupRequest) ProtoMessage() {}

func (x *RegisterGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_group_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterGroupRequest.ProtoReflect.Descriptor instead.
func (*RegisterGroupRequest) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_group_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterGroupRequest) GetJid() string {
	if x != nil {
		return x.Jid
	}
	return ""
}

func (x *RegisterGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterGroupRequest) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

func (x *RegisterGroupRequest) GetTriggerPattern() string {
	if x != nil {
		return x.TriggerPattern
	}
	return ""
}

func (x *RegisterGroupRequest) GetIsMain() bool {
	if x != nil {
		return x.IsMain
	}
	return false
}

func (x *RegisterGroupRequest) GetRequiresTrigger() bool {
	if x != nil {
		return x.RequiresTrigger
	}
	return false
}

func (x *RegisterGroupRequest) GetContainerConfigJson() string {
	if x != nil {
		return x.ContainerConfigJson
	}
	return ""
}

type GetGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jid           string                 `protobuf:"bytes,1,opt,name=jid,proto3" json:"jid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupRequest) Reset() {
	*x = GetGroupRequest{}
	mi := &file_kraclaw_v1_group_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupRequest) ProtoMessage() {}

func (x *GetGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_group_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupRequest.ProtoReflect.Descriptor instead.
func (*GetGroupRequest) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_group_proto_rawDescGZIP(), []int{2}
}

func (x *GetGroupRequest) GetJid() string {
	if x != nil {
		return x.Jid
	}
	return ""
}

type ListGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsRequest) Reset() {
	*x = ListGroupsRequest{}
	mi := &file_kraclaw_v1_group_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsRequest) ProtoMessage() {}

func (x *ListGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_group_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListGroupsRequest) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_group_proto_rawDescGZIP(), []int{3}
}

type ListGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*Group               `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsResponse) Reset() {
	*x = ListGroupsResponse{}
	mi := &file_kraclaw_v1_group_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsResponse) ProtoMessage() {}

func (x *ListGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_group_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListGroupsResponse) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_group_proto_rawDescGZIP(), []int{4}
}

func (x *ListGroupsResponse) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

type UnregisterGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jid           string                 `protobuf:"bytes,1,opt,name=jid,proto3" json:"jid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterGroupRequest) Reset() {
	*x = UnregisterGroupRequest{}
	mi := &file_kraclaw_v1_group_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterGroupRequest) ProtoMessage() {}

func (x *UnregisterGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_group_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterGroupRequest.ProtoReflect.Descriptor instead.
func (*UnregisterGroupRequest) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_group_proto_rawDescGZIP(), []int{5}
}

func (x *UnregisterGroupRequest) GetJid() string {
	if x != nil {
		return x.Jid
	}
	return ""
}

type UnregisterGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterGroupResponse) Reset() {
	*x = UnregisterGroupResponse{}
	mi := &file_kraclaw_v1_group_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterGroupResponse) ProtoMessage() {}

func (x *UnregisterGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_group_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterGroupResponse.ProtoReflect.Descriptor instead.
func (*UnregisterGroupResponse) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_group_proto_rawDescGZIP(), []int{6}
}

type SenderAllowlistEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ChatJid       string                 `protobuf:"bytes,2,opt,name=chat_jid,json=chatJid,proto3" json:"chat_jid,omitempty"`
	AllowPattern  string                 `protobuf:"bytes,3,opt,name=allow_pattern,json=allowPattern,proto3" json:"allow_pattern,omitempty"`
	Mode          string                 `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"` // trigger, drop
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SenderAllowlistEntry) Reset() {
	*x = SenderAllowlistEntry{}
	mi := &file_kraclaw_v1_group_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SenderAllowlistEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SenderAllowlistEntry) ProtoMessage() {}

func (x *SenderAllowlistEntry) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_group_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SenderAllowlistEntry.ProtoReflect.Descriptor instead.
func (*SenderAllowlistEntry) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_group_proto_rawDescGZIP(), []int{7}
}

func (x *SenderAllowlistEntry) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SenderAllowlistEntry) GetChatJid() string {
	if x != nil {
		return x.ChatJid
	}
	return ""
}

func (x *SenderAllowlistEntry) GetAllowPattern() string {
	if x != nil {
		return x.AllowPattern
	}
	return ""
}

func (x *SenderAllowlistEntry) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type SenderAllowlist struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Entries       []*SenderAllowlistEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SenderAllowlist) Reset() {
	*x = SenderAllowlist{}
	mi := &file_kraclaw_v1_group_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SenderAllowlist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SenderAllowlist) ProtoMessage() {}

func (x *SenderAllowlist) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_group_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SenderAllowlist.ProtoReflect.Descriptor instead.
func (*SenderAllowlist) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_group_proto_rawDescGZIP(), []int{8}
}

func (x *SenderAllowlist) GetEntries() []*SenderAllowlistEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type GetSenderAllowlistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatJid       string                 `protobuf:"bytes,1,opt,name=chat_jid,json=chatJid,proto3" json:"chat_jid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSenderAllowlistRequest) Reset() {
	*x = GetSenderAllowlistRequest{}
	mi := &file_kraclaw_v1_group_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSenderAllowlistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSenderAllowlistRequest) ProtoMessage() {}

func (x *GetSenderAllowlistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_group_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSenderAllowlistRequest.ProtoReflect.Descriptor instead.
func (*GetSenderAllowlistRequest) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_group_proto_rawDescGZIP(), []int{9}
}

func (x *GetSenderAllowlistRequest) GetChatJid() string {
	if x != nil {
		return x.ChatJid
	}
	return ""
}

type UpdateSenderAllowlistRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	ChatJid       string                  `protobuf:"bytes,1,opt,name=chat_jid,json=chatJid,proto3" json:"chat_jid,omitempty"`
	Entries       []*SenderAllowlistEntry `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSenderAllowlistRequest) Reset() {
	*x = UpdateSenderAllowlistRequest{}
	mi := &file_kraclaw_v1_group_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSenderAllowlistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSenderAllowlistRequest) ProtoMessage() {}

func (x *UpdateSenderAllowlistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_group_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSenderAllowlistRequest.ProtoReflect.Descriptor instead.
func (*UpdateSenderAllowlistRequest) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_group_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateSenderAllowlistRequest) GetChatJid() string {
	if x != nil {
		return x.ChatJid
	}
	return ""
}

func (x *UpdateSenderAllowlistRequest) GetEntries() []*SenderAllowlistEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type ListProvidersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvidersRequest) Reset() {
	*x = ListProvidersRequest{}
	mi := &file_kraclaw_v1_group_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvidersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvidersRequest) ProtoMessage() {}

func (x *ListProvidersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_group_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvidersRequest.ProtoReflect.Descriptor instead.
func (*ListProvidersRequest) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_group_proto_rawDescGZIP(), []int{11}
}

type ListProvidersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*ProviderInfo        `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvidersResponse) Reset() {
	*x = ListProvidersResponse{}
	mi := &file_kraclaw_v1_group_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvidersResponse) ProtoMessage() {}

func (x *ListProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_group_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvidersResponse.ProtoReflect.Descriptor instead.
func (*ListProvidersResponse) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_group_proto_rawDescGZIP(), []int{12}
}

func (x *ListProvidersResponse) GetProviders() []*ProviderInfo {
	if x != nil {
		return x.Providers
	}
	return nil
}

type ProviderInfo struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName  string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	DefaultModel string                 `protobuf:"bytes,3,opt,name=default_model,json=defaultModel,proto3" json:"default_model,omitempty"`
	Models       []*ModelInfo           `protobuf:"bytes,4,rep,name=models,proto3" json:"models,omitempty"`
	// auth_mode is "api_key" or "chatgpt". Empty = "api_key" for forward compatibility.
	AuthMode      string `protobuf:"bytes,5,opt,name=auth_mode,json=authMode,proto3" json:"auth_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderInfo) Reset() {
	*x = ProviderInfo{}
	mi := &file_kraclaw_v1_group_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderInfo) ProtoMessage() {}

func (x *ProviderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_group_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderInfo.ProtoReflect.Descriptor instead.
func (*ProviderInfo) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_group_proto_rawDescGZIP(), []int{13}
}

func (x *ProviderInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProviderInfo) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ProviderInfo) GetDefaultModel() string {
	if x != nil {
		return x.DefaultModel
	}
	return ""
}

func (x *ProviderInfo) GetModels() []*ModelInfo {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *ProviderInfo) GetAuthMode() string {
	if x != nil {
		return x.AuthMode
	}
	return ""
}

type ModelInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelInfo) Reset() {
	*x = ModelInfo{}
	mi := &file_kraclaw_v1_group_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfo) ProtoMessage() {}

func (x *ModelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_group_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfo.ProtoReflect.Descriptor instead.
func (*ModelInfo) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_group_proto_rawDescGZIP(), []int{14}
}

func (x *ModelInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ModelInfo) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

var File_kraclaw_v1_group_proto protoreflect.FileDescriptor

const file_kraclaw_v1_group_proto_rawDesc = "" +
	"\n" +
	"\x16kraclaw/v1/group.proto\x12\n" +
	"kraclaw.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9d\x02\n" +
	"\x05Group\x12\x10\n" +
	"\x03jid\x18\x01 \x01(\tR\x03jid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06folder\x18\x03 \x01(\tR\x06folder\x12'\n" +
	"\x0ftrigger_pattern\x18\x04 \x01(\tR\x0etriggerPattern\x12\x17\n" +
	"\ais_main\x18\x05 \x01(\bR\x06isMain\x12)\n" +
	"\x10requires_trigger\x18\x06 \x01(\bR\x0frequiresTrigger\x122\n" +
	"\x15container_config_json\x18\a \x01(\tR\x13containerConfigJson\x125\n" +
	"\badded_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\aaddedAt\"\xf5\x01\n" +
	"\x14RegisterGroupRequest\x12\x10\n" +
	"\x03jid\x18\x01 \x01(\tR\x03jid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06folder\x18\x03 \x01(\tR\x06folder\x12'\n" +
	"\x0ftrigger_pattern\x18\x04 \x01(\tR\x0etriggerPattern\x12\x17\n" +
	"\ais_main\x18\x05 \x01(\bR\x06isMain\x12)\n" +
	"\x10requires_trigger\x18\x06 \x01(\bR\x0frequiresTrigger\x122\n" +
	"\x15container_config_json\x18\a \x01(\tR\x13containerConfigJson\"#\n" +
	"\x0fGetGroupRequest\x12\x10\n" +
	"\x03jid\x18\x01 \x01(\tR\x03jid\"\x13\n" +
	"\x11ListGroupsRequest\"?\n" +
	"\x12ListGroupsResponse\x12)\n" +
	"\x06groups\x18\x01 \x03(\v2\x11.kraclaw.v1.GroupR\x06groups\"*\n" +
	"\x16UnregisterGroupRequest\x12\x10\n" +
	"\x03jid\x18\x01 \x01(\tR\x03jid\"\x19\n" +
	"\x17UnregisterGroupResponse\"z\n" +
	"\x14SenderAllowlistEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bchat_jid\x18\x02 \x01(\tR\achatJid\x12#\n" +
	"\rallow_pattern\x18\x03 \x01(\tR\fallowPattern\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\tR\x04mode\"M\n" +
	"\x0fSenderAllowlist\x12:\n" +
	"\aentries\x18\x01 \x03(\v2 .kraclaw.v1.SenderAllowlistEntryR\aentries\"6\n" +
	"\x19GetSenderAllowlistRequest\x12\x19\n" +
	"\bchat_jid\x18\x01 \x01(\tR\achatJid\"u\n" +
	"\x1cUpdateSenderAllowlistRequest\x12\x19\n" +
	"\bchat_jid\x18\x01 \x01(\tR\achatJid\x12:\n" +
	"\aentries\x18\x02 \x03(\v2 .kraclaw.v1.SenderAllowlistEntryR\aentries\"\x16\n" +
	"\x14ListProvidersRequest\"O\n" +
	"\x15ListProvidersResponse\x126\n" +
	"\tproviders\x18\x01 \x03(\v2\x18.kraclaw.v1.ProviderInfoR\tproviders\"\xb2\x01\n" +
	"\fProviderInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12#\n" +
	"\rdefault_model\x18\x03 \x01(\tR\fdefaultModel\x12-\n" +
	"\x06models\x18\x04 \x03(\v2\x15.kraclaw.v1.ModelInfoR\x06models\x12\x1b\n" +
	"\tauth_mode\x18\x05 \x01(\tR\bauthMode\">\n" +
	"\tModelInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName2\xc9\x04\n" +
	"\fGroupService\x12D\n" +
	"\rRegisterGroup\x12 .kraclaw.v1.RegisterGroupRequest\x1a\x11.kraclaw.v1.Group\x12K\n" +
	"\n" +
	"ListGroups\x12\x1d.kraclaw.v1.ListGroupsRequest\x1a\x1e.kraclaw.v1.ListGroupsResponse\x12:\n" +
	"\bGetGroup\x12\x1b.kraclaw.v1.GetGroupRequest\x1a\x11.kraclaw.v1.Group\x12Z\n" +
	"\x0fUnregisterGroup\x12\".kraclaw.v1.UnregisterGroupRequest\x1a#.kraclaw.v1.UnregisterGroupResponse\x12X\n" +
	"\x12GetSenderAllowlist\x12%.kraclaw.v1.GetSenderAllowlistRequest\x1a\x1b.kraclaw.v1.SenderAllowlist\x12^\n" +
	"\x15UpdateSenderAllowlist\x12(.kraclaw.v1.UpdateSenderAllowlistRequest\x1a\x1b.kraclaw.v1.SenderAllowlist\x12T\n" +
	"\rListProviders\x12 .kraclaw.v1.ListProvidersRequest\x1a!.kraclaw.v1.ListProvidersResponseB\x9b\x01\n" +
	"\x0ecom.kraclaw.v1B\n" +
	"GroupProtoP\x01Z4github.com/johanssonvincent/kraclaw/pkg/pb/kraclawv1\xa2\x02\x03KXX\xaa\x02\n" +
	"Kraclaw.V1\xca\x02\n" +
	"Kraclaw\\V1\xe2\x02\x16Kraclaw\\V1\\GPBMetadata\xea\x02\vKraclaw::V1b\x06proto3"

var (
	file_kraclaw_v1_group_proto_rawDescOnce sync.Once
	file_kraclaw_v1_group_proto_rawDescData []byte
)

func file_kraclaw_v1_group_proto_rawDescGZIP() []byte {
	file_kraclaw_v1_group_proto_rawDescOnce.Do(func() {
		file_kraclaw_v1_group_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kraclaw_v1_group_proto_rawDesc), len(file_kraclaw_v1_group_proto_rawDesc)))
	})
	return file_kraclaw_v1_group_proto_rawDescData
}

var file_kraclaw_v1_group_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_kraclaw_v1_group_proto_goTypes = []any{
	(*Group)(nil),                        // 0: kraclaw.v1.Group
	(*RegisterGroupRequest)(nil),         // 1: kraclaw.v1.RegisterGroupRequest
	(*GetGroupRequest)(nil),              // 2: kraclaw.v1.GetGroupRequest
	(*ListGroupsRequest)(nil),            // 3: kraclaw.v1.ListGroupsRequest
	(*ListGroupsResponse)(nil),           // 4: kraclaw.v1.ListGroupsResponse
	(*UnregisterGroupRequest)(nil),       // 5: kraclaw.v1.UnregisterGroupRequest
	(*UnregisterGroupResponse)(nil),      // 6: kraclaw.v1.UnregisterGroupResponse
	(*SenderAllowlistEntry)(nil),         // 7: kraclaw.v1.SenderAllowlistEntry
	(*SenderAllowlist)(nil),              // 8: kraclaw.v1.SenderAllowlist
	(*GetSenderAllowlistRequest)(nil),    // 9: kraclaw.v1.GetSenderAllowlistRequest
	(*UpdateSenderAllowlistRequest)(nil), // 10: kraclaw.v1.UpdateSenderAllowlistRequest
	(*ListProvidersRequest)(nil),         // 11: kraclaw.v1.ListProvidersRequest
	(*ListProvidersResponse)(nil),        // 12: kraclaw.v1.ListProvidersResponse
	(*ProviderInfo)(nil),                 // 13: kraclaw.v1.ProviderInfo
	(*ModelInfo)(nil),                    // 14: kraclaw.v1.ModelInfo
	(*timestamppb.Timestamp)(nil),        // 15: google.protobuf.Timestamp
}
var file_kraclaw_v1_group_proto_depIdxs = []int32{
	15, // 0: kraclaw.v1.Group.added_at:type_name -> google.protobuf.Timestamp
	0,  // 1: kraclaw.v1.ListGroupsResponse.groups:type_name -> kraclaw.v1.Group
	7,  // 2: kraclaw.v1.SenderAllowlist.entries:type_name -> kraclaw.v1.SenderAllowlistEntry
	7,  // 3: kraclaw.v1.UpdateSenderAllowlistRequest.entries:type_name -> kraclaw.v1.SenderAllowlistEntry
	13, // 4: kraclaw.v1.ListProvidersResponse.providers:type_name -> kraclaw.v1.ProviderInfo
	14, // 5: kraclaw.v1.ProviderInfo.models:type_name -> kraclaw.v1.ModelInfo
	1,  // 6: kraclaw.v1.GroupService.RegisterGroup:input_type -> kraclaw.v1.RegisterGroupRequest
	3,  // 7: kraclaw.v1.GroupService.ListGroups:input_type -> kraclaw.v1.ListGroupsRequest
	2,  // 8: kraclaw.v1.GroupService.GetGroup:input_type -> kraclaw.v1.GetGroupRequest
	5,  // 9: kraclaw.v1.GroupService.UnregisterGroup:input_type -> kraclaw.v1.UnregisterGroupRequest
	9,  // 10: kraclaw.v1.GroupService.GetSenderAllowlist:input_type -> kraclaw.v1.GetSenderAllowlistRequest
	10, // 11: kraclaw.v1.GroupService.UpdateSenderAllowlist:input_type -> kraclaw.v1.UpdateSenderAllowlistRequest
	11, // 12: kraclaw.v1.GroupService.ListProviders:input_type -> kraclaw.v1.ListProvidersRequest
	0,  // 13: kraclaw.v1.GroupService.RegisterGroup:output_type -> kraclaw.v1.Group
	4,  // 14: kraclaw.v1.GroupService.ListGroups:output_type -> kraclaw.v1.ListGroupsResponse
	0,  // 15: kraclaw.v1.GroupService.GetGroup:output_type -> kraclaw.v1.Group
	6,  // 16: kraclaw.v1.GroupService.UnregisterGroup:output_type -> kraclaw.v1.UnregisterGroupResponse
	8,  // 17: kraclaw.v1.GroupService.GetSenderAllowlist:output_type -> kraclaw.v1.SenderAllowlist
	8,  // 18: kraclaw.v1.GroupService.UpdateSenderAllowlist:output_type -> kraclaw.v1.SenderAllowlist
	12, // 19: kraclaw.v1.GroupService.ListProviders:output_type -> kraclaw.v1.ListProvidersResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_kraclaw_v1_group_proto_init() }
func file_kraclaw_v1_group_proto_init() {
	if File_kraclaw_v1_group_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kraclaw_v1_group_proto_rawDesc), len(file_kraclaw_v1_group_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kraclaw_v1_group_proto_goTypes,
		DependencyIndexes: file_kraclaw_v1_group_proto_depIdxs,
		MessageInfos:      file_kraclaw_v1_group_proto_msgTypes,
	}.Build()
	File_kraclaw_v1_group_proto = out.File
	file_kraclaw_v1_group_proto_goTypes = nil
	file_kraclaw_v1_group_proto_depIdxs = nil
}
