// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kraclaw/v1/task.proto

package kraclawv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupFolder   string                 `protobuf:"bytes,2,opt,name=group_folder,json=groupFolder,proto3" json:"group_folder,omitempty"`
	ChatJid       string                 `protobuf:"bytes,3,opt,name=chat_jid,json=chatJid,proto3" json:"chat_jid,omitempty"`
	Prompt        string                 `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`
	ScheduleType  string                 `protobuf:"bytes,5,opt,name=schedule_type,json=scheduleType,proto3" json:"schedule_type,omitempty"` // cron, interval, once
	ScheduleValue string                 `protobuf:"bytes,6,opt,name=schedule_value,json=scheduleValue,proto3" json:"schedule_value,omitempty"`
	ContextMode   string                 `protobuf:"bytes,7,opt,name=context_mode,json=contextMode,proto3" json:"context_mode,omitempty"` // group, isolated
	NextRun       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=next_run,json=nextRun,proto3" json:"next_run,omitempty"`
	LastRun       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_run,json=lastRun,proto3" json:"last_run,omitempty"`
	LastResult    string                 `protobuf:"bytes,10,opt,name=last_result,json=lastResult,proto3" json:"last_result,omitempty"`
	Status        string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"` // active, paused, completed
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_kraclaw_v1_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_task_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetGroupFolder() string {
	if x != nil {
		return x.GroupFolder
	}
	return ""
}

func (x *Task) GetChatJid() string {
	if x != nil {
		return x.ChatJid
	}
	return ""
}

func (x *Task) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *Task) GetScheduleType() string {
	if x != nil {
		return x.ScheduleType
	}
	return ""
}

func (x *Task) GetScheduleValue() string {
	if x != nil {
		return x.ScheduleValue
	}
	return ""
}

func (x *Task) GetContextMode() string {
	if x != nil {
		return x.ContextMode
	}
	return ""
}

func (x *Task) GetNextRun() *timestamppb.Timestamp {
	if x != nil {
		return x.NextRun
	}
	return nil
}

func (x *Task) GetLastRun() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRun
	}
	return nil
}

func (x *Task) GetLastResult() string {
	if x != nil {
		return x.LastResult
	}
	return ""
}

func (x *Task) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Task) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupFolder   string                 `protobuf:"bytes,1,opt,name=group_folder,json=groupFolder,proto3" json:"group_folder,omitempty"`
	ChatJid       string                 `protobuf:"bytes,2,opt,name=chat_jid,json=chatJid,proto3" json:"chat_jid,omitempty"`
	Prompt        string                 `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	ScheduleType  string                 `protobuf:"bytes,4,opt,name=schedule_type,json=scheduleType,proto3" json:"schedule_type,omitempty"`
	ScheduleValue string                 `protobuf:"bytes,5,opt,name=schedule_value,json=scheduleValue,proto3" json:"schedule_value,omitempty"`
	ContextMode   string                 `protobuf:"bytes,6,opt,name=context_mode,json=contextMode,proto3" json:"context_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_kraclaw_v1_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_task_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTaskRequest) GetGroupFolder() string {
	if x != nil {
		return x.GroupFolder
	}
	return ""
}

func (x *CreateTaskRequest) GetChatJid() string {
	if x != nil {
		return x.ChatJid
	}
	return ""
}

func (x *CreateTaskRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *CreateTaskRequest) GetScheduleType() string {
	if x != nil {
		return x.ScheduleType
	}
	return ""
}

func (x *CreateTaskRequest) GetScheduleValue() string {
	if x != nil {
		return x.ScheduleValue
	}
	return ""
}

func (x *CreateTaskRequest) GetContextMode() string {
	if x != nil {
		return x.ContextMode
	}
	return ""
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_kraclaw_v1_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_task_proto_rawDescGZIP(), []int{2}
}

func (x *GetTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupFolder   string                 `protobuf:"bytes,1,opt,name=group_folder,json=groupFolder,proto3" json:"group_folder,omitempty"` // optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_kraclaw_v1_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_task_proto_rawDescGZIP(), []int{3}
}

func (x *ListTasksRequest) GetGroupFolder() string {
	if x != nil {
		return x.GroupFolder
	}
	return ""
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_kraclaw_v1_task_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_task_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_task_proto_rawDescGZIP(), []int{4}
}

func (x *ListTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type UpdateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	ScheduleType  string                 `protobuf:"bytes,3,opt,name=schedule_type,json=scheduleType,proto3" json:"schedule_type,omitempty"`
	ScheduleValue string                 `protobuf:"bytes,4,opt,name=schedule_value,json=scheduleValue,proto3" json:"schedule_value,omitempty"`
	ContextMode   string                 `protobuf:"bytes,5,opt,name=context_mode,json=contextMode,proto3" json:"context_mode,omitempty"`
	GroupFolder   string                 `protobuf:"bytes,6,opt,name=group_folder,json=groupFolder,proto3" json:"group_folder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskRequest) Reset() {
	*x = UpdateTaskRequest{}
	mi := &file_kraclaw_v1_task_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskRequest) ProtoMessage() {}

func (x *UpdateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_task_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_task_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTaskRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *UpdateTaskRequest) GetScheduleType() string {
	if x != nil {
		return x.ScheduleType
	}
	return ""
}

func (x *UpdateTaskRequest) GetScheduleValue() string {
	if x != nil {
		return x.ScheduleValue
	}
	return ""
}

func (x *UpdateTaskRequest) GetContextMode() string {
	if x != nil {
		return x.ContextMode
	}
	return ""
}

func (x *UpdateTaskRequest) GetGroupFolder() string {
	if x != nil {
		return x.GroupFolder
	}
	return ""
}

type PauseTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseTaskRequest) Reset() {
	*x = PauseTaskRequest{}
	mi := &file_kraclaw_v1_task_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseTaskRequest) ProtoMessage() {}

func (x *PauseTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_task_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseTaskRequest.ProtoReflect.Descriptor instead.
func (*PauseTaskRequest) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_task_proto_rawDescGZIP(), []int{6}
}

func (x *PauseTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ResumeTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeTaskRequest) Reset() {
	*x = ResumeTaskRequest{}
	mi := &file_kraclaw_v1_task_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeTaskRequest) ProtoMessage() {}

func (x *ResumeTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_task_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeTaskRequest.ProtoReflect.Descriptor instead.
func (*ResumeTaskRequest) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_task_proto_rawDescGZIP(), []int{7}
}

func (x *ResumeTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_kraclaw_v1_task_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_task_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_task_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskResponse) Reset() {
	*x = DeleteTaskResponse{}
	mi := &file_kraclaw_v1_task_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskResponse) ProtoMessage() {}

func (x *DeleteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_task_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskResponse.ProtoReflect.Descriptor instead.
func (*DeleteTaskResponse) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_task_proto_rawDescGZIP(), []int{9}
}

var File_kraclaw_v1_task_proto protoreflect.FileDescriptor

const file_kraclaw_v1_task_proto_rawDesc = "" +
	"\n" +
	"\x15kraclaw/v1/task.proto\x12\n" +
	"kraclaw.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbd\x03\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fgroup_folder\x18\x02 \x01(\tR\vgroupFolder\x12\x19\n" +
	"\bchat_jid\x18\x03 \x01(\tR\achatJid\x12\x16\n" +
	"\x06prompt\x18\x04 \x01(\tR\x06prompt\x12#\n" +
	"\rschedule_type\x18\x05 \x01(\tR\fscheduleType\x12%\n" +
	"\x0eschedule_value\x18\x06 \x01(\tR\rscheduleValue\x12!\n" +
	"\fcontext_mode\x18\a \x01(\tR\vcontextMode\x125\n" +
	"\bnext_run\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\anextRun\x125\n" +
	"\blast_run\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\alastRun\x12\x1f\n" +
	"\vlast_result\x18\n" +
	" \x01(\tR\n" +
	"lastResult\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xd8\x01\n" +
	"\x11CreateTaskRequest\x12!\n" +
	"\fgroup_folder\x18\x01 \x01(\tR\vgroupFolder\x12\x19\n" +
	"\bchat_jid\x18\x02 \x01(\tR\achatJid\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\x12#\n" +
	"\rschedule_type\x18\x04 \x01(\tR\fscheduleType\x12%\n" +
	"\x0eschedule_value\x18\x05 \x01(\tR\rscheduleValue\x12!\n" +
	"\fcontext_mode\x18\x06 \x01(\tR\vcontextMode\" \n" +
	"\x0eGetTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"5\n" +
	"\x10ListTasksRequest\x12!\n" +
	"\fgroup_folder\x18\x01 \x01(\tR\vgroupFolder\";\n" +
	"\x11ListTasksResponse\x12&\n" +
	"\x05tasks\x18\x01 \x03(\v2\x10.kraclaw.v1.TaskR\x05tasks\"\xcd\x01\n" +
	"\x11UpdateTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12#\n" +
	"\rschedule_type\x18\x03 \x01(\tR\fscheduleType\x12%\n" +
	"\x0eschedule_value\x18\x04 \x01(\tR\rscheduleValue\x12!\n" +
	"\fcontext_mode\x18\x05 \x01(\tR\vcontextMode\x12!\n" +
	"\fgroup_folder\x18\x06 \x01(\tR\vgroupFolder\"\"\n" +
	"\x10PauseTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"#\n" +
	"\x11ResumeTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"#\n" +
	"\x11DeleteTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x14\n" +
	"\x12DeleteTaskResponse2\xd7\x03\n" +
	"\vTaskService\x12=\n" +
	"\n" +
	"CreateTask\x12\x1d.kraclaw.v1.CreateTaskRequest\x1a\x10.kraclaw.v1.Task\x127\n" +
	"\aGetTask\x12\x1a.kraclaw.v1.GetTaskRequest\x1a\x10.kraclaw.v1.Task\x12H\n" +
	"\tListTasks\x12\x1c.kraclaw.v1.ListTasksRequest\x1a\x1d.kraclaw.v1.ListTasksResponse\x12=\n" +
	"\n" +
	"UpdateTask\x12\x1d.kraclaw.v1.UpdateTaskRequest\x1a\x10.kraclaw.v1.Task\x12;\n" +
	"\tPauseTask\x12\x1c.kraclaw.v1.PauseTaskRequest\x1a\x10.kraclaw.v1.Task\x12=\n" +
	"\n" +
	"ResumeTask\x12\x1d.kraclaw.v1.ResumeTaskRequest\x1a\x10.kraclaw.v1.Task\x12K\n" +
	"\n" +
	"DeleteTask\x12\x1d.kraclaw.v1.DeleteTaskRequest\x1a\x1e.kraclaw.v1.DeleteTaskResponseB\x9a\x01\n" +
	"\x0ecom.kraclaw.v1B\tTaskProtoP\x01Z4github.com/johanssonvincent/kraclaw/pkg/pb/kraclawv1\xa2\x02\x03KXX\xaa\x02\n" +
	"Kraclaw.V1\xca\x02\n" +
	"Kraclaw\\V1\xe2\x02\x16Kraclaw\\V1\\GPBMetadata\xea\x02\vKraclaw::V1b\x06proto3"

var (
	file_kraclaw_v1_task_proto_rawDescOnce sync.Once
	file_kraclaw_v1_task_proto_rawDescData []byte
)

func file_kraclaw_v1_task_proto_rawDescGZIP() []byte {
	file_kraclaw_v1_task_proto_rawDescOnce.Do(func() {
		file_kraclaw_v1_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kraclaw_v1_task_proto_rawDesc), len(file_kraclaw_v1_task_proto_rawDesc)))
	})
	return file_kraclaw_v1_task_proto_rawDescData
}

var file_kraclaw_v1_task_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_kraclaw_v1_task_proto_goTypes = []any{
	(*Task)(nil),                  // 0: kraclaw.v1.Task
	(*CreateTaskRequest)(nil),     // 1: kraclaw.v1.CreateTaskRequest
	(*GetTaskRequest)(nil),        // 2: kraclaw.v1.GetTaskRequest
	(*ListTasksRequest)(nil),      // 3: kraclaw.v1.ListTasksRequest
	(*ListTasksResponse)(nil),     // 4: kraclaw.v1.ListTasksResponse
	(*UpdateTaskRequest)(nil),     // 5: kraclaw.v1.UpdateTaskRequest
	(*PauseTaskRequest)(nil),      // 6: kraclaw.v1.PauseTaskRequest
	(*ResumeTaskRequest)(nil),     // 7: kraclaw.v1.ResumeTaskRequest
	(*DeleteTaskRequest)(nil),     // 8: kraclaw.v1.DeleteTaskRequest
	(*DeleteTaskResponse)(nil),    // 9: kraclaw.v1.DeleteTaskResponse
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_kraclaw_v1_task_proto_depIdxs = []int32{
	10, // 0: kraclaw.v1.Task.next_run:type_name -> google.protobuf.Timestamp
	10, // 1: kraclaw.v1.Task.last_run:type_name -> google.protobuf.Timestamp
	10, // 2: kraclaw.v1.Task.created_at:type_name -> google.protobuf.Timestamp
	0,  // 3: kraclaw.v1.ListTasksResponse.tasks:type_name -> kraclaw.v1.Task
	1,  // 4: kraclaw.v1.TaskService.CreateTask:input_type -> kraclaw.v1.CreateTaskRequest
	2,  // 5: kraclaw.v1.TaskService.GetTask:input_type -> kraclaw.v1.GetTaskRequest
	3,  // 6: kraclaw.v1.TaskService.ListTasks:input_type -> kraclaw.v1.ListTasksRequest
	5,  // 7: kraclaw.v1.TaskService.UpdateTask:input_type -> kraclaw.v1.UpdateTaskRequest
	6,  // 8: kraclaw.v1.TaskService.PauseTask:input_type -> kraclaw.v1.PauseTaskRequest
	7,  // 9: kraclaw.v1.TaskService.ResumeTask:input_type -> kraclaw.v1.ResumeTaskRequest
	8,  // 10: kraclaw.v1.TaskService.DeleteTask:input_type -> kraclaw.v1.DeleteTaskRequest
	0,  // 11: kraclaw.v1.TaskService.CreateTask:output_type -> kraclaw.v1.Task
	0,  // 12: kraclaw.v1.TaskService.GetTask:output_type -> kraclaw.v1.Task
	4,  // 13: kraclaw.v1.TaskService.ListTasks:output_type -> kraclaw.v1.ListTasksResponse
	0,  // 14: kraclaw.v1.TaskService.UpdateTask:output_type -> kraclaw.v1.Task
	0,  // 15: kraclaw.v1.TaskService.PauseTask:output_type -> kraclaw.v1.Task
	0,  // 16: kraclaw.v1.TaskService.ResumeTask:output_type -> kraclaw.v1.Task
	9,  // 17: kraclaw.v1.TaskService.DeleteTask:output_type -> kraclaw.v1.DeleteTaskResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_kraclaw_v1_task_proto_init() }
func file_kraclaw_v1_task_proto_init() {
	if File_kraclaw_v1_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kraclaw_v1_task_proto_rawDesc), len(file_kraclaw_v1_task_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kraclaw_v1_task_proto_goTypes,
		DependencyIndexes: file_kraclaw_v1_task_proto_depIdxs,
		MessageInfos:      file_kraclaw_v1_task_proto_msgTypes,
	}.Build()
	File_kraclaw_v1_task_proto = out.File
	file_kraclaw_v1_task_proto_goTypes = nil
	file_kraclaw_v1_task_proto_depIdxs = nil
}
