// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kraclaw/v1/admin.proto

package kraclawv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_kraclaw_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_admin_proto_rawDescGZIP(), []int{0}
}

type ServerStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Version           string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	ActiveSandboxes   int32                  `protobuf:"varint,2,opt,name=active_sandboxes,json=activeSandboxes,proto3" json:"active_sandboxes,omitempty"`
	ConnectedChannels int32                  `protobuf:"varint,3,opt,name=connected_channels,json=connectedChannels,proto3" json:"connected_channels,omitempty"`
	PendingMessages   int32                  `protobuf:"varint,4,opt,name=pending_messages,json=pendingMessages,proto3" json:"pending_messages,omitempty"`
	ActiveTasks       int32                  `protobuf:"varint,5,opt,name=active_tasks,json=activeTasks,proto3" json:"active_tasks,omitempty"`
	UptimeSince       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=uptime_since,json=uptimeSince,proto3" json:"uptime_since,omitempty"`
	MysqlConnected    bool                   `protobuf:"varint,7,opt,name=mysql_connected,json=mysqlConnected,proto3" json:"mysql_connected,omitempty"`
	RedisConnected    bool                   `protobuf:"varint,8,opt,name=redis_connected,json=redisConnected,proto3" json:"redis_connected,omitempty"`
	K8SConnected      bool                   `protobuf:"varint,9,opt,name=k8s_connected,json=k8sConnected,proto3" json:"k8s_connected,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ServerStatus) Reset() {
	*x = ServerStatus{}
	mi := &file_kraclaw_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStatus) ProtoMessage() {}

func (x *ServerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStatus.ProtoReflect.Descriptor instead.
func (*ServerStatus) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *ServerStatus) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServerStatus) GetActiveSandboxes() int32 {
	if x != nil {
		return x.ActiveSandboxes
	}
	return 0
}

func (x *ServerStatus) GetConnectedChannels() int32 {
	if x != nil {
		return x.ConnectedChannels
	}
	return 0
}

func (x *ServerStatus) GetPendingMessages() int32 {
	if x != nil {
		return x.PendingMessages
	}
	return 0
}

func (x *ServerStatus) GetActiveTasks() int32 {
	if x != nil {
		return x.ActiveTasks
	}
	return 0
}

func (x *ServerStatus) GetUptimeSince() *timestamppb.Timestamp {
	if x != nil {
		return x.UptimeSince
	}
	return nil
}

func (x *ServerStatus) GetMysqlConnected() bool {
	if x != nil {
		return x.MysqlConnected
	}
	return false
}

func (x *ServerStatus) GetRedisConnected() bool {
	if x != nil {
		return x.RedisConnected
	}
	return false
}

func (x *ServerStatus) GetK8SConnected() bool {
	if x != nil {
		return x.K8SConnected
	}
	return false
}

type StreamEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventTypes    []string               `protobuf:"bytes,1,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"` // filter by type, empty = all
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_kraclaw_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *StreamEventsRequest) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_kraclaw_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *Event) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Event) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Event) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsRequest) Reset() {
	*x = GetMetricsRequest{}
	mi := &file_kraclaw_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsRequest) ProtoMessage() {}

func (x *GetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_admin_proto_rawDescGZIP(), []int{4}
}

type Metrics struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TotalMessagesReceived int64                  `protobuf:"varint,1,opt,name=total_messages_received,json=totalMessagesReceived,proto3" json:"total_messages_received,omitempty"`
	TotalMessagesSent     int64                  `protobuf:"varint,2,opt,name=total_messages_sent,json=totalMessagesSent,proto3" json:"total_messages_sent,omitempty"`
	TotalSandboxesCreated int64                  `protobuf:"varint,3,opt,name=total_sandboxes_created,json=totalSandboxesCreated,proto3" json:"total_sandboxes_created,omitempty"`
	TotalTasksExecuted    int64                  `protobuf:"varint,4,opt,name=total_tasks_executed,json=totalTasksExecuted,proto3" json:"total_tasks_executed,omitempty"`
	ProxyRequests         int64                  `protobuf:"varint,5,opt,name=proxy_requests,json=proxyRequests,proto3" json:"proxy_requests,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_kraclaw_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_admin_proto_rawDescGZIP(), []int{5}
}

func (x *Metrics) GetTotalMessagesReceived() int64 {
	if x != nil {
		return x.TotalMessagesReceived
	}
	return 0
}

func (x *Metrics) GetTotalMessagesSent() int64 {
	if x != nil {
		return x.TotalMessagesSent
	}
	return 0
}

func (x *Metrics) GetTotalSandboxesCreated() int64 {
	if x != nil {
		return x.TotalSandboxesCreated
	}
	return 0
}

func (x *Metrics) GetTotalTasksExecuted() int64 {
	if x != nil {
		return x.TotalTasksExecuted
	}
	return 0
}

func (x *Metrics) GetProxyRequests() int64 {
	if x != nil {
		return x.ProxyRequests
	}
	return 0
}

var File_kraclaw_v1_admin_proto protoreflect.FileDescriptor

const file_kraclaw_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x16kraclaw/v1/admin.proto\x12\n" +
	"kraclaw.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x12\n" +
	"\x10GetStatusRequest\"\x86\x03\n" +
	"\fServerStatus\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12)\n" +
	"\x10active_sandboxes\x18\x02 \x01(\x05R\x0factiveSandboxes\x12-\n" +
	"\x12connected_channels\x18\x03 \x01(\x05R\x11connectedChannels\x12)\n" +
	"\x10pending_messages\x18\x04 \x01(\x05R\x0fpendingMessages\x12!\n" +
	"\factive_tasks\x18\x05 \x01(\x05R\vactiveTasks\x12=\n" +
	"\fuptime_since\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vuptimeSince\x12'\n" +
	"\x0fmysql_connected\x18\a \x01(\bR\x0emysqlConnected\x12'\n" +
	"\x0fredis_connected\x18\b \x01(\bR\x0eredisConnected\x12#\n" +
	"\rk8s_connected\x18\t \x01(\bR\fk8sConnected\"6\n" +
	"\x13StreamEventsRequest\x12\x1f\n" +
	"\vevent_types\x18\x01 \x03(\tR\n" +
	"eventTypes\"\x81\x02\n" +
	"\x05Event\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12;\n" +
	"\bmetadata\x18\x05 \x03(\v2\x1f.kraclaw.v1.Event.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x13\n" +
	"\x11GetMetricsRequest\"\x82\x02\n" +
	"\aMetrics\x126\n" +
	"\x17total_messages_received\x18\x01 \x01(\x03R\x15totalMessagesReceived\x12.\n" +
	"\x13total_messages_sent\x18\x02 \x01(\x03R\x11totalMessagesSent\x126\n" +
	"\x17total_sandboxes_created\x18\x03 \x01(\x03R\x15totalSandboxesCreated\x120\n" +
	"\x14total_tasks_executed\x18\x04 \x01(\x03R\x12totalTasksExecuted\x12%\n" +
	"\x0eproxy_requests\x18\x05 \x01(\x03R\rproxyRequests2\xdb\x01\n" +
	"\fAdminService\x12C\n" +
	"\tGetStatus\x12\x1c.kraclaw.v1.GetStatusRequest\x1a\x18.kraclaw.v1.ServerStatus\x12D\n" +
	"\fStreamEvents\x12\x1f.kraclaw.v1.StreamEventsRequest\x1a\x11.kraclaw.v1.Event0\x01\x12@\n" +
	"\n" +
	"GetMetrics\x12\x1d.kraclaw.v1.GetMetricsRequest\x1a\x13.kraclaw.v1.MetricsB\x9b\x01\n" +
	"\x0ecom.kraclaw.v1B\n" +
	"AdminProtoP\x01Z4github.com/johanssonvincent/kraclaw/pkg/pb/kraclawv1\xa2\x02\x03KXX\xaa\x02\n" +
	"Kraclaw.V1\xca\x02\n" +
	"Kraclaw\\V1\xe2\x02\x16Kraclaw\\V1\\GPBMetadata\xea\x02\vKraclaw::V1b\x06proto3"

var (
	file_kraclaw_v1_admin_proto_rawDescOnce sync.Once
	file_kraclaw_v1_admin_proto_rawDescData []byte
)

func file_kraclaw_v1_admin_proto_rawDescGZIP() []byte {
	file_kraclaw_v1_admin_proto_rawDescOnce.Do(func() {
		file_kraclaw_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kraclaw_v1_admin_proto_rawDesc), len(file_kraclaw_v1_admin_proto_rawDesc)))
	})
	return file_kraclaw_v1_admin_proto_rawDescData
}

var file_kraclaw_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_kraclaw_v1_admin_proto_goTypes = []any{
	(*GetStatusRequest)(nil),      // 0: kraclaw.v1.GetStatusRequest
	(*ServerStatus)(nil),          // 1: kraclaw.v1.ServerStatus
	(*StreamEventsRequest)(nil),   // 2: kraclaw.v1.StreamEventsRequest
	(*Event)(nil),                 // 3: kraclaw.v1.Event
	(*GetMetricsRequest)(nil),     // 4: kraclaw.v1.GetMetricsRequest
	(*Metrics)(nil),               // 5: kraclaw.v1.Metrics
	nil,                           // 6: kraclaw.v1.Event.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_kraclaw_v1_admin_proto_depIdxs = []int32{
	7, // 0: kraclaw.v1.ServerStatus.uptime_since:type_name -> google.protobuf.Timestamp
	7, // 1: kraclaw.v1.Event.timestamp:type_name -> google.protobuf.Timestamp
	6, // 2: kraclaw.v1.Event.metadata:type_name -> kraclaw.v1.Event.MetadataEntry
	0, // 3: kraclaw.v1.AdminService.GetStatus:input_type -> kraclaw.v1.GetStatusRequest
	2, // 4: kraclaw.v1.AdminService.StreamEvents:input_type -> kraclaw.v1.StreamEventsRequest
	4, // 5: kraclaw.v1.AdminService.GetMetrics:input_type -> kraclaw.v1.GetMetricsRequest
	1, // 6: kraclaw.v1.AdminService.GetStatus:output_type -> kraclaw.v1.ServerStatus
	3, // 7: kraclaw.v1.AdminService.StreamEvents:output_type -> kraclaw.v1.Event
	5, // 8: kraclaw.v1.AdminService.GetMetrics:output_type -> kraclaw.v1.Metrics
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_kraclaw_v1_admin_proto_init() }
func file_kraclaw_v1_admin_proto_init() {
	if File_kraclaw_v1_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kraclaw_v1_admin_proto_rawDesc), len(file_kraclaw_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kraclaw_v1_admin_proto_goTypes,
		DependencyIndexes: file_kraclaw_v1_admin_proto_depIdxs,
		MessageInfos:      file_kraclaw_v1_admin_proto_msgTypes,
	}.Build()
	File_kraclaw_v1_admin_proto = out.File
	file_kraclaw_v1_admin_proto_goTypes = nil
	file_kraclaw_v1_admin_proto_depIdxs = nil
}
