// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kraclaw/v1/channel.proto

package kraclawv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChannelStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Connected     bool                   `protobuf:"varint,2,opt,name=connected,proto3" json:"connected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelStatus) Reset() {
	*x = ChannelStatus{}
	mi := &file_kraclaw_v1_channel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelStatus) ProtoMessage() {}

func (x *ChannelStatus) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_channel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelStatus.ProtoReflect.Descriptor instead.
func (*ChannelStatus) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_channel_proto_rawDescGZIP(), []int{0}
}

func (x *ChannelStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChannelStatus) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

type ListChannelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChannelsRequest) Reset() {
	*x = ListChannelsRequest{}
	mi := &file_kraclaw_v1_channel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChannelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChannelsRequest) ProtoMessage() {}

func (x *ListChannelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_channel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChannelsRequest.ProtoReflect.Descriptor instead.
func (*ListChannelsRequest) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_channel_proto_rawDescGZIP(), []int{1}
}

type ListChannelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channels      []*ChannelStatus       `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChannelsResponse) Reset() {
	*x = ListChannelsResponse{}
	mi := &file_kraclaw_v1_channel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChannelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChannelsResponse) ProtoMessage() {}

func (x *ListChannelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_channel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChannelsResponse.ProtoReflect.Descriptor instead.
func (*ListChannelsResponse) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_channel_proto_rawDescGZIP(), []int{2}
}

func (x *ListChannelsResponse) GetChannels() []*ChannelStatus {
	if x != nil {
		return x.Channels
	}
	return nil
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatJid       string                 `protobuf:"bytes,1,opt,name=chat_jid,json=chatJid,proto3" json:"chat_jid,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Sender        string                 `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	SenderName    string                 `protobuf:"bytes,4,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_kraclaw_v1_channel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_channel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_channel_proto_rawDescGZIP(), []int{3}
}

func (x *SendMessageRequest) GetChatJid() string {
	if x != nil {
		return x.ChatJid
	}
	return ""
}

func (x *SendMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SendMessageRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *SendMessageRequest) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_kraclaw_v1_channel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_channel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_channel_proto_rawDescGZIP(), []int{4}
}

type StreamInboundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatJid       string                 `protobuf:"bytes,1,opt,name=chat_jid,json=chatJid,proto3" json:"chat_jid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamInboundRequest) Reset() {
	*x = StreamInboundRequest{}
	mi := &file_kraclaw_v1_channel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamInboundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamInboundRequest) ProtoMessage() {}

func (x *StreamInboundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_channel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamInboundRequest.ProtoReflect.Descriptor instead.
func (*StreamInboundRequest) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_channel_proto_rawDescGZIP(), []int{5}
}

func (x *StreamInboundRequest) GetChatJid() string {
	if x != nil {
		return x.ChatJid
	}
	return ""
}

type InboundMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ChatJid       string                 `protobuf:"bytes,2,opt,name=chat_jid,json=chatJid,proto3" json:"chat_jid,omitempty"`
	Sender        string                 `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	SenderName    string                 `protobuf:"bytes,4,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Channel       string                 `protobuf:"bytes,7,opt,name=channel,proto3" json:"channel,omitempty"`
	IsGroup       bool                   `protobuf:"varint,8,opt,name=is_group,json=isGroup,proto3" json:"is_group,omitempty"`
	Model         string                 `protobuf:"bytes,9,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboundMessage) Reset() {
	*x = InboundMessage{}
	mi := &file_kraclaw_v1_channel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboundMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboundMessage) ProtoMessage() {}

func (x *InboundMessage) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_channel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboundMessage.ProtoReflect.Descriptor instead.
func (*InboundMessage) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_channel_proto_rawDescGZIP(), []int{6}
}

func (x *InboundMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InboundMessage) GetChatJid() string {
	if x != nil {
		return x.ChatJid
	}
	return ""
}

func (x *InboundMessage) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *InboundMessage) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *InboundMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *InboundMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *InboundMessage) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *InboundMessage) GetIsGroup() bool {
	if x != nil {
		return x.IsGroup
	}
	return false
}

func (x *InboundMessage) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

var File_kraclaw_v1_channel_proto protoreflect.FileDescriptor

const file_kraclaw_v1_channel_proto_rawDesc = "" +
	"\n" +
	"\x18kraclaw/v1/channel.proto\x12\n" +
	"kraclaw.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"A\n" +
	"\rChannelStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tconnected\x18\x02 \x01(\bR\tconnected\"\x15\n" +
	"\x13ListChannelsRequest\"M\n" +
	"\x14ListChannelsResponse\x125\n" +
	"\bchannels\x18\x01 \x03(\v2\x19.kraclaw.v1.ChannelStatusR\bchannels\"|\n" +
	"\x12SendMessageRequest\x12\x19\n" +
	"\bchat_jid\x18\x01 \x01(\tR\achatJid\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x16\n" +
	"\x06sender\x18\x03 \x01(\tR\x06sender\x12\x1f\n" +
	"\vsender_name\x18\x04 \x01(\tR\n" +
	"senderName\"\x15\n" +
	"\x13SendMessageResponse\"1\n" +
	"\x14StreamInboundRequest\x12\x19\n" +
	"\bchat_jid\x18\x01 \x01(\tR\achatJid\"\x93\x02\n" +
	"\x0eInboundMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bchat_jid\x18\x02 \x01(\tR\achatJid\x12\x16\n" +
	"\x06sender\x18\x03 \x01(\tR\x06sender\x12\x1f\n" +
	"\vsender_name\x18\x04 \x01(\tR\n" +
	"senderName\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\achannel\x18\a \x01(\tR\achannel\x12\x19\n" +
	"\bis_group\x18\b \x01(\bR\aisGroup\x12\x14\n" +
	"\x05model\x18\t \x01(\tR\x05model2\x84\x02\n" +
	"\x0eChannelService\x12Q\n" +
	"\fListChannels\x12\x1f.kraclaw.v1.ListChannelsRequest\x1a .kraclaw.v1.ListChannelsResponse\x12N\n" +
	"\vSendMessage\x12\x1e.kraclaw.v1.SendMessageRequest\x1a\x1f.kraclaw.v1.SendMessageResponse\x12O\n" +
	"\rStreamInbound\x12 .kraclaw.v1.StreamInboundRequest\x1a\x1a.kraclaw.v1.InboundMessage0\x01B\x9d\x01\n" +
	"\x0ecom.kraclaw.v1B\fChannelProtoP\x01Z4github.com/johanssonvincent/kraclaw/pkg/pb/kraclawv1\xa2\x02\x03KXX\xaa\x02\n" +
	"Kraclaw.V1\xca\x02\n" +
	"Kraclaw\\V1\xe2\x02\x16Kraclaw\\V1\\GPBMetadata\xea\x02\vKraclaw::V1b\x06proto3"

var (
	file_kraclaw_v1_channel_proto_rawDescOnce sync.Once
	file_kraclaw_v1_channel_proto_rawDescData []byte
)

func file_kraclaw_v1_channel_proto_rawDescGZIP() []byte {
	file_kraclaw_v1_channel_proto_rawDescOnce.Do(func() {
		file_kraclaw_v1_channel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kraclaw_v1_channel_proto_rawDesc), len(file_kraclaw_v1_channel_proto_rawDesc)))
	})
	return file_kraclaw_v1_channel_proto_rawDescData
}

var file_kraclaw_v1_channel_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_kraclaw_v1_channel_proto_goTypes = []any{
	(*ChannelStatus)(nil),         // 0: kraclaw.v1.ChannelStatus
	(*ListChannelsRequest)(nil),   // 1: kraclaw.v1.ListChannelsRequest
	(*ListChannelsResponse)(nil),  // 2: kraclaw.v1.ListChannelsResponse
	(*SendMessageRequest)(nil),    // 3: kraclaw.v1.SendMessageRequest
	(*SendMessageResponse)(nil),   // 4: kraclaw.v1.SendMessageResponse
	(*StreamInboundRequest)(nil),  // 5: kraclaw.v1.StreamInboundRequest
	(*InboundMessage)(nil),        // 6: kraclaw.v1.InboundMessage
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_kraclaw_v1_channel_proto_depIdxs = []int32{
	0, // 0: kraclaw.v1.ListChannelsResponse.channels:type_name -> kraclaw.v1.ChannelStatus
	7, // 1: kraclaw.v1.InboundMessage.timestamp:type_name -> google.protobuf.Timestamp
	1, // 2: kraclaw.v1.ChannelService.ListChannels:input_type -> kraclaw.v1.ListChannelsRequest
	3, // 3: kraclaw.v1.ChannelService.SendMessage:input_type -> kraclaw.v1.SendMessageRequest
	5, // 4: kraclaw.v1.ChannelService.StreamInbound:input_type -> kraclaw.v1.StreamInboundRequest
	2, // 5: kraclaw.v1.ChannelService.ListChannels:output_type -> kraclaw.v1.ListChannelsResponse
	4, // 6: kraclaw.v1.ChannelService.SendMessage:output_type -> kraclaw.v1.SendMessageResponse
	6, // 7: kraclaw.v1.ChannelService.StreamInbound:output_type -> kraclaw.v1.InboundMessage
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_kraclaw_v1_channel_proto_init() }
func file_kraclaw_v1_channel_proto_init() {
	if File_kraclaw_v1_channel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kraclaw_v1_channel_proto_rawDesc), len(file_kraclaw_v1_channel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kraclaw_v1_channel_proto_goTypes,
		DependencyIndexes: file_kraclaw_v1_channel_proto_depIdxs,
		MessageInfos:      file_kraclaw_v1_channel_proto_msgTypes,
	}.Build()
	File_kraclaw_v1_channel_proto = out.File
	file_kraclaw_v1_channel_proto_goTypes = nil
	file_kraclaw_v1_channel_proto_depIdxs = nil
}
