// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: kraclaw/v1/sandbox.proto

package kraclawv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Sandbox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	GroupFolder   string                 `protobuf:"bytes,2,opt,name=group_folder,json=groupFolder,proto3" json:"group_folder,omitempty"`
	GroupJid      string                 `protobuf:"bytes,3,opt,name=group_jid,json=groupJid,proto3" json:"group_jid,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"` // pending, running, completed, failed
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	SessionId     string                 `protobuf:"bytes,7,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sandbox) Reset() {
	*x = Sandbox{}
	mi := &file_kraclaw_v1_sandbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sandbox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sandbox) ProtoMessage() {}

func (x *Sandbox) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_sandbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sandbox.ProtoReflect.Descriptor instead.
func (*Sandbox) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_sandbox_proto_rawDescGZIP(), []int{0}
}

func (x *Sandbox) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Sandbox) GetGroupFolder() string {
	if x != nil {
		return x.GroupFolder
	}
	return ""
}

func (x *Sandbox) GetGroupJid() string {
	if x != nil {
		return x.GroupJid
	}
	return ""
}

func (x *Sandbox) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Sandbox) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Sandbox) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *Sandbox) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CreateSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupFolder   string                 `protobuf:"bytes,1,opt,name=group_folder,json=groupFolder,proto3" json:"group_folder,omitempty"`
	GroupJid      string                 `protobuf:"bytes,2,opt,name=group_jid,json=groupJid,proto3" json:"group_jid,omitempty"`
	Prompt        string                 `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	IsMain        bool                   `protobuf:"varint,5,opt,name=is_main,json=isMain,proto3" json:"is_main,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,6,opt,name=timeout,proto3" json:"timeout,omitempty"`
	AssistantName string                 `protobuf:"bytes,7,opt,name=assistant_name,json=assistantName,proto3" json:"assistant_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSandboxRequest) Reset() {
	*x = CreateSandboxRequest{}
	mi := &file_kraclaw_v1_sandbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSandboxRequest) ProtoMessage() {}

func (x *CreateSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_sandbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSandboxRequest.ProtoReflect.Descriptor instead.
func (*CreateSandboxRequest) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_sandbox_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSandboxRequest) GetGroupFolder() string {
	if x != nil {
		return x.GroupFolder
	}
	return ""
}

func (x *CreateSandboxRequest) GetGroupJid() string {
	if x != nil {
		return x.GroupJid
	}
	return ""
}

func (x *CreateSandboxRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *CreateSandboxRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateSandboxRequest) GetIsMain() bool {
	if x != nil {
		return x.IsMain
	}
	return false
}

func (x *CreateSandboxRequest) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *CreateSandboxRequest) GetAssistantName() string {
	if x != nil {
		return x.AssistantName
	}
	return ""
}

type CreateSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sandbox       *Sandbox               `protobuf:"bytes,1,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSandboxResponse) Reset() {
	*x = CreateSandboxResponse{}
	mi := &file_kraclaw_v1_sandbox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSandboxResponse) ProtoMessage() {}

func (x *CreateSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_sandbox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSandboxResponse.ProtoReflect.Descriptor instead.
func (*CreateSandboxResponse) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_sandbox_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSandboxResponse) GetSandbox() *Sandbox {
	if x != nil {
		return x.Sandbox
	}
	return nil
}

type GetSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSandboxRequest) Reset() {
	*x = GetSandboxRequest{}
	mi := &file_kraclaw_v1_sandbox_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSandboxRequest) ProtoMessage() {}

func (x *GetSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_sandbox_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSandboxRequest.ProtoReflect.Descriptor instead.
func (*GetSandboxRequest) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_sandbox_proto_rawDescGZIP(), []int{3}
}

func (x *GetSandboxRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListSandboxesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSandboxesRequest) Reset() {
	*x = ListSandboxesRequest{}
	mi := &file_kraclaw_v1_sandbox_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSandboxesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSandboxesRequest) ProtoMessage() {}

func (x *ListSandboxesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_sandbox_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSandboxesRequest.ProtoReflect.Descriptor instead.
func (*ListSandboxesRequest) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_sandbox_proto_rawDescGZIP(), []int{4}
}

type ListSandboxesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sandboxes     []*Sandbox             `protobuf:"bytes,1,rep,name=sandboxes,proto3" json:"sandboxes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSandboxesResponse) Reset() {
	*x = ListSandboxesResponse{}
	mi := &file_kraclaw_v1_sandbox_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSandboxesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSandboxesResponse) ProtoMessage() {}

func (x *ListSandboxesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_sandbox_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSandboxesResponse.ProtoReflect.Descriptor instead.
func (*ListSandboxesResponse) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_sandbox_proto_rawDescGZIP(), []int{5}
}

func (x *ListSandboxesResponse) GetSandboxes() []*Sandbox {
	if x != nil {
		return x.Sandboxes
	}
	return nil
}

type StopSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopSandboxRequest) Reset() {
	*x = StopSandboxRequest{}
	mi := &file_kraclaw_v1_sandbox_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSandboxRequest) ProtoMessage() {}

func (x *StopSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_sandbox_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSandboxRequest.ProtoReflect.Descriptor instead.
func (*StopSandboxRequest) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_sandbox_proto_rawDescGZIP(), []int{6}
}

func (x *StopSandboxRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type StopSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopSandboxResponse) Reset() {
	*x = StopSandboxResponse{}
	mi := &file_kraclaw_v1_sandbox_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSandboxResponse) ProtoMessage() {}

func (x *StopSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_sandbox_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSandboxResponse.ProtoReflect.Descriptor instead.
func (*StopSandboxResponse) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_sandbox_proto_rawDescGZIP(), []int{7}
}

type PipeSandboxInputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	GroupFolder   string                 `protobuf:"bytes,2,opt,name=group_folder,json=groupFolder,proto3" json:"group_folder,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipeSandboxInputRequest) Reset() {
	*x = PipeSandboxInputRequest{}
	mi := &file_kraclaw_v1_sandbox_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipeSandboxInputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipeSandboxInputRequest) ProtoMessage() {}

func (x *PipeSandboxInputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_sandbox_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipeSandboxInputRequest.ProtoReflect.Descriptor instead.
func (*PipeSandboxInputRequest) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_sandbox_proto_rawDescGZIP(), []int{8}
}

func (x *PipeSandboxInputRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PipeSandboxInputRequest) GetGroupFolder() string {
	if x != nil {
		return x.GroupFolder
	}
	return ""
}

func (x *PipeSandboxInputRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type PipeSandboxInputResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipeSandboxInputResponse) Reset() {
	*x = PipeSandboxInputResponse{}
	mi := &file_kraclaw_v1_sandbox_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipeSandboxInputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipeSandboxInputResponse) ProtoMessage() {}

func (x *PipeSandboxInputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_sandbox_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipeSandboxInputResponse.ProtoReflect.Descriptor instead.
func (*PipeSandboxInputResponse) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_sandbox_proto_rawDescGZIP(), []int{9}
}

type StreamLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Follow        bool                   `protobuf:"varint,2,opt,name=follow,proto3" json:"follow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLogsRequest) Reset() {
	*x = StreamLogsRequest{}
	mi := &file_kraclaw_v1_sandbox_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLogsRequest) ProtoMessage() {}

func (x *StreamLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_sandbox_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLogsRequest.ProtoReflect.Descriptor instead.
func (*StreamLogsRequest) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_sandbox_proto_rawDescGZIP(), []int{10}
}

func (x *StreamLogsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StreamLogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Container     string                 `protobuf:"bytes,2,opt,name=container,proto3" json:"container,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_kraclaw_v1_sandbox_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_sandbox_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_sandbox_proto_rawDescGZIP(), []int{11}
}

func (x *LogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogEntry) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StreamOutputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	GroupFolder   string                 `protobuf:"bytes,2,opt,name=group_folder,json=groupFolder,proto3" json:"group_folder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamOutputRequest) Reset() {
	*x = StreamOutputRequest{}
	mi := &file_kraclaw_v1_sandbox_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOutputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOutputRequest) ProtoMessage() {}

func (x *StreamOutputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_sandbox_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOutputRequest.ProtoReflect.Descriptor instead.
func (*StreamOutputRequest) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_sandbox_proto_rawDescGZIP(), []int{12}
}

func (x *StreamOutputRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StreamOutputRequest) GetGroupFolder() string {
	if x != nil {
		return x.GroupFolder
	}
	return ""
}

type SandboxOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // text, session_update, error
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	NewSessionId  string                 `protobuf:"bytes,3,opt,name=new_session_id,json=newSessionId,proto3" json:"new_session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxOutput) Reset() {
	*x = SandboxOutput{}
	mi := &file_kraclaw_v1_sandbox_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxOutput) ProtoMessage() {}

func (x *SandboxOutput) ProtoReflect() protoreflect.Message {
	mi := &file_kraclaw_v1_sandbox_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxOutput.ProtoReflect.Descriptor instead.
func (*SandboxOutput) Descriptor() ([]byte, []int) {
	return file_kraclaw_v1_sandbox_proto_rawDescGZIP(), []int{13}
}

func (x *SandboxOutput) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SandboxOutput) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SandboxOutput) GetNewSessionId() string {
	if x != nil {
		return x.NewSessionId
	}
	return ""
}

var File_kraclaw_v1_sandbox_proto protoreflect.FileDescriptor

const file_kraclaw_v1_sandbox_proto_rawDesc = "" +
	"\n" +
	"\x18kraclaw/v1/sandbox.proto\x12\n" +
	"kraclaw.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\x84\x02\n" +
	"\aSandbox\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fgroup_folder\x18\x02 \x01(\tR\vgroupFolder\x12\x1b\n" +
	"\tgroup_jid\x18\x03 \x01(\tR\bgroupJid\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x129\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x1d\n" +
	"\n" +
	"session_id\x18\a \x01(\tR\tsessionId\"\x82\x02\n" +
	"\x14CreateSandboxRequest\x12!\n" +
	"\fgroup_folder\x18\x01 \x01(\tR\vgroupFolder\x12\x1b\n" +
	"\tgroup_jid\x18\x02 \x01(\tR\bgroupJid\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12\x17\n" +
	"\ais_main\x18\x05 \x01(\bR\x06isMain\x123\n" +
	"\atimeout\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12%\n" +
	"\x0eassistant_name\x18\a \x01(\tR\rassistantName\"F\n" +
	"\x15CreateSandboxResponse\x12-\n" +
	"\asandbox\x18\x01 \x01(\v2\x13.kraclaw.v1.SandboxR\asandbox\"'\n" +
	"\x11GetSandboxRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x16\n" +
	"\x14ListSandboxesRequest\"J\n" +
	"\x15ListSandboxesResponse\x121\n" +
	"\tsandboxes\x18\x01 \x03(\v2\x13.kraclaw.v1.SandboxR\tsandboxes\"(\n" +
	"\x12StopSandboxRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x15\n" +
	"\x13StopSandboxResponse\"d\n" +
	"\x17PipeSandboxInputRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fgroup_folder\x18\x02 \x01(\tR\vgroupFolder\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"\x1a\n" +
	"\x18PipeSandboxInputResponse\"?\n" +
	"\x11StreamLogsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06follow\x18\x02 \x01(\bR\x06follow\"|\n" +
	"\bLogEntry\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1c\n" +
	"\tcontainer\x18\x02 \x01(\tR\tcontainer\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"L\n" +
	"\x13StreamOutputRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fgroup_folder\x18\x02 \x01(\tR\vgroupFolder\"c\n" +
	"\rSandboxOutput\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12$\n" +
	"\x0enew_session_id\x18\x03 \x01(\tR\fnewSessionId2\xce\x04\n" +
	"\x0eSandboxService\x12T\n" +
	"\rCreateSandbox\x12 .kraclaw.v1.CreateSandboxRequest\x1a!.kraclaw.v1.CreateSandboxResponse\x12@\n" +
	"\n" +
	"GetSandbox\x12\x1d.kraclaw.v1.GetSandboxRequest\x1a\x13.kraclaw.v1.Sandbox\x12T\n" +
	"\rListSandboxes\x12 .kraclaw.v1.ListSandboxesRequest\x1a!.kraclaw.v1.ListSandboxesResponse\x12N\n" +
	"\vStopSandbox\x12\x1e.kraclaw.v1.StopSandboxRequest\x1a\x1f.kraclaw.v1.StopSandboxResponse\x12]\n" +
	"\x10PipeSandboxInput\x12#.kraclaw.v1.PipeSandboxInputRequest\x1a$.kraclaw.v1.PipeSandboxInputResponse\x12J\n" +
	"\x11StreamSandboxLogs\x12\x1d.kraclaw.v1.StreamLogsRequest\x1a\x14.kraclaw.v1.LogEntry0\x01\x12S\n" +
	"\x13StreamSandboxOutput\x12\x1f.kraclaw.v1.StreamOutputRequest\x1a\x19.kraclaw.v1.SandboxOutput0\x01B\x9d\x01\n" +
	"\x0ecom.kraclaw.v1B\fSandboxProtoP\x01Z4github.com/johanssonvincent/kraclaw/pkg/pb/kraclawv1\xa2\x02\x03KXX\xaa\x02\n" +
	"Kraclaw.V1\xca\x02\n" +
	"Kraclaw\\V1\xe2\x02\x16Kraclaw\\V1\\GPBMetadata\xea\x02\vKraclaw::V1b\x06proto3"

var (
	file_kraclaw_v1_sandbox_proto_rawDescOnce sync.Once
	file_kraclaw_v1_sandbox_proto_rawDescData []byte
)

func file_kraclaw_v1_sandbox_proto_rawDescGZIP() []byte {
	file_kraclaw_v1_sandbox_proto_rawDescOnce.Do(func() {
		file_kraclaw_v1_sandbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kraclaw_v1_sandbox_proto_rawDesc), len(file_kraclaw_v1_sandbox_proto_rawDesc)))
	})
	return file_kraclaw_v1_sandbox_proto_rawDescData
}

var file_kraclaw_v1_sandbox_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_kraclaw_v1_sandbox_proto_goTypes = []any{
	(*Sandbox)(nil),                  // 0: kraclaw.v1.Sandbox
	(*CreateSandboxRequest)(nil),     // 1: kraclaw.v1.CreateSandboxRequest
	(*CreateSandboxResponse)(nil),    // 2: kraclaw.v1.CreateSandboxResponse
	(*GetSandboxRequest)(nil),        // 3: kraclaw.v1.GetSandboxRequest
	(*ListSandboxesRequest)(nil),     // 4: kraclaw.v1.ListSandboxesRequest
	(*ListSandboxesResponse)(nil),    // 5: kraclaw.v1.ListSandboxesResponse
	(*StopSandboxRequest)(nil),       // 6: kraclaw.v1.StopSandboxRequest
	(*StopSandboxResponse)(nil),      // 7: kraclaw.v1.StopSandboxResponse
	(*PipeSandboxInputRequest)(nil),  // 8: kraclaw.v1.PipeSandboxInputRequest
	(*PipeSandboxInputResponse)(nil), // 9: kraclaw.v1.PipeSandboxInputResponse
	(*StreamLogsRequest)(nil),        // 10: kraclaw.v1.StreamLogsRequest
	(*LogEntry)(nil),                 // 11: kraclaw.v1.LogEntry
	(*StreamOutputRequest)(nil),      // 12: kraclaw.v1.StreamOutputRequest
	(*SandboxOutput)(nil),            // 13: kraclaw.v1.SandboxOutput
	(*timestamppb.Timestamp)(nil),    // 14: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),      // 15: google.protobuf.Duration
}
var file_kraclaw_v1_sandbox_proto_depIdxs = []int32{
	14, // 0: kraclaw.v1.Sandbox.start_time:type_name -> google.protobuf.Timestamp
	14, // 1: kraclaw.v1.Sandbox.end_time:type_name -> google.protobuf.Timestamp
	15, // 2: kraclaw.v1.CreateSandboxRequest.timeout:type_name -> google.protobuf.Duration
	0,  // 3: kraclaw.v1.CreateSandboxResponse.sandbox:type_name -> kraclaw.v1.Sandbox
	0,  // 4: kraclaw.v1.ListSandboxesResponse.sandboxes:type_name -> kraclaw.v1.Sandbox
	14, // 5: kraclaw.v1.LogEntry.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 6: kraclaw.v1.SandboxService.CreateSandbox:input_type -> kraclaw.v1.CreateSandboxRequest
	3,  // 7: kraclaw.v1.SandboxService.GetSandbox:input_type -> kraclaw.v1.GetSandboxRequest
	4,  // 8: kraclaw.v1.SandboxService.ListSandboxes:input_type -> kraclaw.v1.ListSandboxesRequest
	6,  // 9: kraclaw.v1.SandboxService.StopSandbox:input_type -> kraclaw.v1.StopSandboxRequest
	8,  // 10: kraclaw.v1.SandboxService.PipeSandboxInput:input_type -> kraclaw.v1.PipeSandboxInputRequest
	10, // 11: kraclaw.v1.SandboxService.StreamSandboxLogs:input_type -> kraclaw.v1.StreamLogsRequest
	12, // 12: kraclaw.v1.SandboxService.StreamSandboxOutput:input_type -> kraclaw.v1.StreamOutputRequest
	2,  // 13: kraclaw.v1.SandboxService.CreateSandbox:output_type -> kraclaw.v1.CreateSandboxResponse
	0,  // 14: kraclaw.v1.SandboxService.GetSandbox:output_type -> kraclaw.v1.Sandbox
	5,  // 15: kraclaw.v1.SandboxService.ListSandboxes:output_type -> kraclaw.v1.ListSandboxesResponse
	7,  // 16: kraclaw.v1.SandboxService.StopSandbox:output_type -> kraclaw.v1.StopSandboxResponse
	9,  // 17: kraclaw.v1.SandboxService.PipeSandboxInput:output_type -> kraclaw.v1.PipeSandboxInputResponse
	11, // 18: kraclaw.v1.SandboxService.StreamSandboxLogs:output_type -> kraclaw.v1.LogEntry
	13, // 19: kraclaw.v1.SandboxService.StreamSandboxOutput:output_type -> kraclaw.v1.SandboxOutput
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_kraclaw_v1_sandbox_proto_init() }
func file_kraclaw_v1_sandbox_proto_init() {
	if File_kraclaw_v1_sandbox_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kraclaw_v1_sandbox_proto_rawDesc), len(file_kraclaw_v1_sandbox_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kraclaw_v1_sandbox_proto_goTypes,
		DependencyIndexes: file_kraclaw_v1_sandbox_proto_depIdxs,
		MessageInfos:      file_kraclaw_v1_sandbox_proto_msgTypes,
	}.Build()
	File_kraclaw_v1_sandbox_proto = out.File
	file_kraclaw_v1_sandbox_proto_goTypes = nil
	file_kraclaw_v1_sandbox_proto_depIdxs = nil
}
